/bin/bash -l -c 'cd /Volumes/Archivo/trabajo/coddea/cl_colmena_court && bundle exec bin/rails runner -e development '\''StudyCase.study_crawler('\''\'\'''\''COLMENA'\''\'\'''\'')'\'''
echo -ne '####                             (12.5%)\r'
/bin/bash -l -c 'cd /Volumes/Archivo/trabajo/coddea/cl_colmena_court && bundle exec bin/rails runner -e development '\''StudyCase.study_crawler('\''\'\'''\''BANMEDICA'\''\'\'''\'')'\'''
echo -ne '########                         (25%)\r'
/bin/bash -l -c 'cd /Volumes/Archivo/trabajo/coddea/cl_colmena_court && bundle exec bin/rails runner -e development '\''StudyCase.study_crawler('\''\'\'''\''CONSALUD'\''\'\'''\'')'\'''
echo -ne '############                     (37.5%)\r'
/bin/bash -l -c 'cd /Volumes/Archivo/trabajo/coddea/cl_colmena_court && bundle exec bin/rails runner -e development '\''StudyCase.study_crawler('\''\'\'''\''CRUZ BLANCA'\''\'\'''\'')'\'''
echo -ne '################                 (50%)\r'
/bin/bash -l -c 'cd /Volumes/Archivo/trabajo/coddea/cl_colmena_court && bundle exec bin/rails runner -e development '\''StudyCase.study_crawler('\''\'\'''\''FERROSALUD'\''\'\'''\'')'\'''
echo -ne '####################             (62.5%)\r'
/bin/bash -l -c 'cd /Volumes/Archivo/trabajo/coddea/cl_colmena_court && bundle exec bin/rails runner -e development '\''StudyCase.study_crawler('\''\'\'''\''FUSAT'\''\'\'''\'')'\'''
echo -ne '########################         (75%)\r'
/bin/bash -l -c 'cd /Volumes/Archivo/trabajo/coddea/cl_colmena_court && bundle exec bin/rails runner -e development '\''StudyCase.study_crawler('\''\'\'''\''MASVIDA'\''\'\'''\'')'\'''
echo -ne '############################     (87.5%)\r'
/bin/bash -l -c 'cd /Volumes/Archivo/trabajo/coddea/cl_colmena_court && bundle exec bin/rails runner -e development '\''StudyCase.study_crawler('\''\'\'''\''ISAPRE FUNDACION'\''\'\'''\'')'\'''
echo -ne '################################ (100%)\r'
echo -ne '\n'