default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_bin

development:
  <<: *default
  database: colmena_court_development
  socket: /tmp/mysql.sock
  username: root
  password: kaosbite

test:
  <<: *default
  database: colmena_court_test
  socket: /tmp/mysql.sock
  username: root
  password: kaosbite

production:
  <<: *default
  database: colmena_court_production
  username: root
  password: reframe2015+-
